# Generated by Django 4.2.6 on 2023-10-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AddField(
            model_name='about',
            name='about_heading',
            field=models.CharField(default='About', max_length=25),
        ),
    ]
